on:
  push:
    branches:
      - main

jobs:
  upload_files:
    environment: deploy
    runs-on: ubuntu-latest
    name: Upload static
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build
        shell: bash
        run: |
          chmod +x "./make.sh"
          "npm install babel-loader"
          "./make.sh"
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './demo'
          remotePath: './plantlang.ink'
